#!/bin/sh
# MD5=cb3c2e839177644d6c11263085582a7c
# Cosmo - the dev box toolkit
# Regular Expression Notes:
# REGEX for host /^(\[\s*(?:all|live|production)\s*\])$/gm
# REGEX for key=val /^(\w*)(?:=)([\"\']?.*[\"\']?)$/gm  # Greedy value regex. Maybe change

main ()
{
    CURRENT_SUM=$(sed -n '3,$p' $0 | md5)
    RECORDED_SUM=$(head -2 cosmo | grep -e 'MD5' | cut -c 7-)
    if [ ! $CURRENT_SUM = $RECORDED_SUM ]; then
        echo "BAD MD5 SUM. POSSIBLE INFECTED SCRIPT! EXITING!"
        exit
    fi

    if [ ! -n "$1" ]
    then
      usage
      exit
    fi

    case "$1" in
      init  ) init;;
      deploy) deploy;;
      *     ) usage;;
    esac
}

usage ()
{
    echo "Usage: $0 <command>\n"
    echo "Where <command> is one of the following:"
    echo "  init,deploy,provision"
}

## Commands
init ()
{
    echo "This utility will walk you through creating a cosmo.config file."
    echo "This config file will serve as the manifest for creating and deploying your project\n"
    echo "Press ^C at any time to quit."
    exit;
}

deploy ()
{
    require_config
    echo "Deploying..."
}

provision ()
{
    # Requires config file to continue
    require_config
    echo "Provisioning..."
}

## Helper Functions
require_config ()
{
    if [ ! -f "cosmo.config" ]
    then
        echo "Config file not found. Please run\n"
        echo "  $0 init\n"
    fi
}

# This is never ran but serves to show how to update the MD5
update_md5 ()
{
    `sed -i '' -e "s/^\# MD5=.*/# MD5=$(sed -n '3,$p' $0 | md5)/g" $0`
}

main $@
