---
- name: Install Mailcatcher Dependencies
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - sqlite3
    - ruby2.3
    - ruby2.3-dev
    - libsqlite3-dev

- name: Install Mailcatcher
  become: true
  command: gem2.3 install mailcatcher -N

- name: Create mailcatcher upstart file
  template:
    src: mailcatcher.conf.j2
    dest: /etc/init/mailcatcher.conf

- name: Enable mailcatcher service
  service: name=mailcatcher enabled=yes state=started

- name: Update php cli settings for mailcatcher
  ini_file: dest=/etc/php/5.6/cli/php.ini create=no option=sendmail_path value='/usr/local/bin/catchmail -f test@test.com' section=sendmail

- name: Update apache2 settings for mailcatcher
  ini_file: dest=/etc/php/5.6/apache2/php.ini create=no option=sendmail_path value='/usr/local/bin/catchmail -f test@test.com' section=sendmail