- name: Add ondrej/php PPA
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install php7.3
  apt:
    name: ['php7.3', 'php7.3-dev',
           'php7.3-common', 'php7.3-mysql', 'php7.3-zip', 'php7.3-bz2', 'php7.3-cli',
           'php7.3-curl', 'php7.3-gd', 'php7.3-cgi', 'php7.3-memcache', 'php7.3-pspell',
           'php7.3-xml', 'php7.3-xmlrpc', 'php7.3-xsl', 'php7.3-sqlite3', 'php7.3-snmp',
           'php7.3-opcache', 'php7.3-mbstring', 'php7.3-imap', 'php7.3-json',
           'php7.3-readline', 'php-pear', 'php-imagick', 'libapache2-mod-php7.3',
           'libmcrypt-dev']
    state: present

- name: pecl install mcrypt
  shell: pecl list | grep mcrypt || yes '' | pecl install mcrypt 1> /dev/null

- name: Enable mcrypt module
  shell: phpenmod mcrypt

- lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = 250M'

- lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regexp: '^post_max_size ='
    line: 'post_max_size = 250M'

- lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regexp: '^display_errors ='
    line: 'display_errors = On'

- name: Restart apache2
  service: name=apache2 state=restarted